### ISSUE TITLE
Version 0.4.0 no longer working

### ISSUE THREAD

**Issue by postretrofuture** [tolbkni/vultr.rb#11]
Version 0.3.5 was working fine. The new version is giving the following error

vagrant up production --provider=vultr
Traceback (most recent call last):
        16: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/bin/vagrant:164:in `<main>'
        15: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/environment.rb:294:in `cli'
        14: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/cli.rb:54:in `execute'
        13: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/plugins/commands/up/command.rb:87:in `execute'
        12: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        11: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:186:in `each'
        10: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
         9: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
         8: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/environment.rb:719:in `machine'
         7: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/vagrantfile.rb:79:in `machine'
         6: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/vagrantfile.rb:79:in `new'
         5: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/machine.rb:146:in `initialize'
         4: from /opt/vagrant/embedded/gems/gems/vagrant-2.1.4/lib/vagrant/machine.rb:526:in `state'
         3: from /root/.vagrant.d/gems/2.5.1/gems/vagrant-vultr-0.1.2/lib/vagrant-vultr/provider.rb:19:in `state'
         2: from /root/.vagrant.d/gems/2.5.1/gems/vagrant-vultr-0.1.2/lib/vagrant-vultr/helpers/client.rb:33:in `server'
         1: from /root/.vagrant.d/gems/2.5.1/gems/vagrant-vultr-0.1.2/lib/vagrant-vultr/helpers/client.rb:26:in `servers'
/root/.vagrant.d/gems/2.5.1/gems/vagrant-vultr-0.1.2/lib/vagrant-vultr/helpers/client.rb:139:in `request': API request failed: Only one filter per request is allowed.. (RuntimeError)

**Comment by tolbkni** [comment]
Thank you for your feedback. I will fix it soon and push a new minor version named 0.4.1
