### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by excid3** [tolbkni/vultr.rb#15]
Hey @tolbkni 👋 

I have been working on this gem to support the Vultr API v2 ([my PR](https://github.com/excid3/vultr.rb/pull/1)).

I'm actively using this in some apps of mine and would love to be able to make releases of the gem. Would you consider adding me as a maintainer of the gem or transferring ownership if you don't want to maintain it anymore?

**Comment by excid3** [comment]
Bump @tolbkni 👀

**Comment by tolbkni** [comment]
I have added you as one of the gem owners in https://rubygems.org. Ownership access will be enabled after you clicks on the confirmation mail.

**Comment by tolbkni** [comment]
If you want to be a contributor of the repo, please tell me.

**Comment by excid3** [comment]
Thanks @tolbkni!

If you wouldn't mind adding me to the repo, I can make issues and PRs for it too. 👍

I think we're just about finished adding tests for the v2 API and can get that released shortly.
