### ISSUE TITLE
ssl_verify: false

### ISSUE THREAD

**Issue by funzoneq** [tolbkni/vultr.rb#7]
Hi,

I would like to use your gem to manage my vultr instances, but I noticed in your gem that you don't verify the SSL certificate on authenticity.

Can you please change this, as there is a valid certificate served on api.vultr.com

Thanks

**Comment by tolbkni** [comment]
Thanks for your advice, I will deal with it later today

**Comment by funzoneq** [comment]
@tolbkni thanks!
