### ISSUE TITLE
Faraday Depndency

### ISSUE THREAD

**Issue by richpeck** [tolbkni/vultr.rb#9]
Can you bump the `faraday` + `faraday_middleware` dependencies to at least `0.10.0` (preferably the latest)? 

It's conflicting with the Azure gem:

![untitled](https://user-images.githubusercontent.com/1104431/44005070-08059bdc-9e65-11e8-9046-509ca7ed7044.png)

**Comment by tolbkni** [comment]
faraday `=0.15.2` is to satisfy the requirement of vultr.
`~> 0.9.2` means `>0.9.2 and <1.0.0`

**Comment by richpeck** [comment]
vultr relies on Faraday 0.9.x - can this dependency be bumped to something 0.1.x+ ? At the moment, it's conflicting with other gems.

**Comment by tolbkni** [comment]
Sorry, I maid a mistake, `~> 0.9.2` means `>0.9.2` and `<0.10`, and `~> 0.9` means `> 0.9` and `< 1.0` only.
I will update this dependency to `~> 0.9` to solve the conflict soon.

**Comment by richpeck** [comment]
Thanks - can you not bump the dependency to ~> 0.10 or higher?
